BEGIN;

-- Core USWC focus ports linked to geographic zones
INSERT INTO ports (code, name, state, country, region, is_california, is_cascadia, is_eca, latitude, longitude, pilotage_url, mx_url, tariff_url, zone_id) VALUES
('LALB', 'Los Angeles / Long Beach', 'CA', 'US', 'SoCal', TRUE, FALSE, TRUE, 33.738000, -118.264000,
 'https://www.portoflosangeles.org/business/pilot-service',
 'https://mxsocal.org/',
  'https://www.polb.com/port-info/tariff/',
  (SELECT id FROM port_zones WHERE code = 'SOCAL')),
('SFBAY', 'San Francisco Bay', 'CA', 'US', 'NorCal', TRUE, FALSE, TRUE, 37.795000, -122.276000,
 'https://sfbarpilots.com/new-operational/',
 'https://www.sfmx.org/bay-area-committees/hsc/',
  NULL,
  (SELECT id FROM port_zones WHERE code = 'NORCAL')),
('PUGET', 'Puget Sound (Seattle/Tacoma)', 'WA', 'US', 'PNW', FALSE, TRUE, TRUE, 47.602000, -122.338000,
 'https://www.pspilots.org/dispatch-information/general-guidelines-for-vessels/',
 'https://marexps.com/',
  NULL,
  (SELECT id FROM port_zones WHERE code = 'PUGET')),
('BELLINGHAM', 'Port of Bellingham', 'WA', 'US', 'PNW', FALSE, TRUE, TRUE, 48.752000, -122.490000,
 'https://www.pspilots.org/dispatch-information/general-guidelines-for-vessels/',
  NULL,
  'https://www.portofbellingham.com/DocumentCenter/View/5930/Tariff-No-1',
  (SELECT id FROM port_zones WHERE code = 'PUGET')),
('COLRIV', 'Columbia River (Astoria/Portland)', 'OR', 'US', 'PNW', FALSE, TRUE, TRUE, 46.190000, -123.831000,
 'https://colrip.com/',
 'https://www.pdxmex.com/resources/',
  NULL,
  (SELECT id FROM port_zones WHERE code = 'COLUMBIA')),
('STKN', 'Port of Stockton', 'CA', 'US', 'Inland-Delta', TRUE, FALSE, TRUE, 37.958000, -121.290000,
  NULL,
  NULL,
  'https://www.portofstockton.com/port-tariff/',
  (SELECT id FROM port_zones WHERE code = 'INLAND'))
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  state = EXCLUDED.state,
  country = EXCLUDED.country,
  region = EXCLUDED.region,
  is_california = EXCLUDED.is_california,
  is_cascadia = EXCLUDED.is_cascadia,
  is_eca = EXCLUDED.is_eca,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  pilotage_url = EXCLUDED.pilotage_url,
  mx_url = EXCLUDED.mx_url,
  tariff_url = EXCLUDED.tariff_url,
  zone_id = EXCLUDED.zone_id;

COMMIT;
