BEGIN;
INSERT INTO port_documents (
    port_code,
    document_name,
    document_code,
    is_mandatory,
    lead_time_hours,
    authority,
    description,
    applies_to_vessel_types,
    applies_if_foreign
) VALUES
    ('ALL_US', 'Notice of Arrival (NOAD)', 'NOAD', TRUE, 96, 'USCG',
     'Submit the electronic Notice of Arrival/Departure through NVMC for every arrival to a U.S. port.',
     NULL, FALSE),
    ('ALL_US', 'CBP Form 3171 - Application-Permit-Customs', 'CBP-3171', TRUE, 24, 'CBP',
     'Advance notice to the local Customs office covering cargo operations, bunkering, and crew changes.',
     NULL, FALSE),
    ('ALL_US', 'Crew Manifest (CBP Form I-418)', 'I-418', TRUE, 24, 'CBP',
     'Crew list required for clearance. Includes all persons employed on board the vessel.',
     NULL, TRUE),
    ('ALL_US', 'Passenger Manifest (CBP Form I-418)', 'I-418-PAX', TRUE, 24, 'CBP',
     'Passenger list for vessels carrying passengers. Submit with crew manifest when applicable.',
     ARRAY['cruise']::text[], TRUE),
    ('ALL_US', 'Ballast Water Management Report', 'NBIC-BWM', TRUE, 24, 'USCG',
     'Report ballast operations to the National Ballast Information Clearinghouse prior to arrival.',
     NULL, FALSE),
    ('ALL_US', 'Advanced Notice for High-Risk Vessels', 'USCG-HRV', TRUE, 96, 'USCG',
     'LNG, cruise, and other high-consequence vessels must coordinate security and safety plans with the Captain of the Port.',
     ARRAY['lng','cruise']::text[], FALSE),
    ('LALB', 'Marine Exchange of Southern California Pre-Arrival Notification', 'MX-SOCAL-PAN', TRUE, 48,
     'Marine Exchange of Southern California',
     'Email or fax the standardized pre-arrival notice covering pilotage, security, and terminal readiness.',
     NULL, FALSE),
    ('LALB', 'Port of Long Beach Berth Application', 'POLB-BERTH', TRUE, 72, 'Port of Long Beach',
     'Terminal agent must lodge berth application and line handling arrangements with the Port of Long Beach.',
     NULL, FALSE),
    ('LALB', 'AQMD Fuel Change Compliance Statement', 'SCAQMD-FUEL', TRUE, 24, 'South Coast AQMD',
     'Document distillate fuel changeover prior to the 24 nm regulatory boundary for emission control compliance.',
     ARRAY['container','tanker','bulk_carrier','general_cargo','vehicle_carrier']::text[], FALSE),
    ('SFBAY', 'San Francisco Bar Pilots Pre-Arrival Worksheet', 'SFBAY-PILOT', TRUE, 24, 'San Francisco Bar Pilots',
     'Provide pilot ladder, draft, maneuvering characteristics, and tug requirements to the San Francisco Bar Pilots dispatcher.',
     NULL, FALSE),
    ('SFBAY', 'San Francisco Marine Exchange Berth Application', 'SFMX-BERTH', TRUE, 48,
     'Marine Exchange of the San Francisco Bay Region',
     'Submit berth application with terminal contact, security zone, and tug assignments.',
     NULL, FALSE),
    ('SFBAY', 'California Marine Invasive Species Program Reporting', 'CA-MISP', TRUE, 24,
     'California State Lands Commission',
     'File the electronic Marine Invasive Species Program ballast water and biofouling report.',
     ARRAY['tanker','lng','bulk_carrier','container','general_cargo']::text[], FALSE),
    ('PUGET', 'Puget Sound Marine Exchange Pre-Arrival Questionnaire', 'PSMX-PAQ', TRUE, 48,
     'Marine Exchange of Puget Sound',
     'Comprehensive pre-arrival worksheet for Puget Sound pilot dispatch and security review.',
     NULL, FALSE),
    ('PUGET', 'Puget Sound Pilots Sailing Plan', 'PSP-SAIL', TRUE, 24, 'Puget Sound Pilots',
     'Final sailing plan confirming draft, tug use, and tide window for Puget Sound transits.',
     NULL, FALSE),
    ('PUGET', 'Washington Department of Ecology Advance Notice of Transfer', 'WA-DOE-ANT', TRUE, 48,
     'Washington Department of Ecology',
     'Report intended oil or bunkering transfers at least 48 hours in advance.',
     ARRAY['tanker','lng']::text[], FALSE),
    ('COLRIV', 'Columbia River Bar Pilots ETA Update', 'CRBP-ETA', TRUE, 24, 'Columbia River Bar Pilots',
     'Provide ETA updates and river draft information for bar crossing coordination.',
     NULL, FALSE),
    ('COLRIV', 'Columbia River Navigation Notice', 'CR-NAV', TRUE, 24, 'USACE Portland District',
     'Notify the Corps of Engineers of deep-draft transits for dredging and navigation safety awareness.',
     NULL, FALSE),
    ('COLRIV', 'Oregon DEQ Ballast Water Report', 'OR-DEQ-BW', TRUE, 24, 'Oregon Department of Environmental Quality',
     'Submit state ballast water management report covering exchange or treatment method.',
     ARRAY['tanker','bulk_carrier','container','general_cargo']::text[], FALSE),
    ('STKN', 'Port of Stockton Berth Application', 'STKN-BERTH', TRUE, 72, 'Port of Stockton',
     'Submit berth application with cargo plan, draft, and tug requirements for the inland transit.',
     NULL, FALSE),
    ('STKN', 'California Inland Oil Transfer Notification', 'CA-OTN', TRUE, 48, 'California Office of Spill Prevention and Response',
     'Notify OSPR prior to any oil transfer operations within the Stockton Deepwater Channel.',
     ARRAY['tanker','lng']::text[], FALSE),
    ('STKN', 'San Joaquin River Transit Plan', 'SJ-TRANSIT', TRUE, 24, 'USCG Sector San Francisco',
     'Provide detailed transit plan for pilot coordination through the San Joaquin River system.',
     NULL, FALSE);
COMMIT;
