services:
  - type: web
    name: maritime-mvp-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker src.maritime_mvp.api.main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 90
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false            # paste your Supabase DSN during Blueprint creation
      - key: PSIX_WSDL
        value: https://cgmix.uscg.mil/xml/PSIXData.asmx?WSDL
      - key: PSIX_VERIFY_SSL
        value: "false"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: maritime-cache
          property: connectionString  # redis://... or rediss://...
  - type: keyvalue
    name: maritime-cache
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
