# render.yaml (repo root)
services:
  - type: web
    name: maritime-mvp-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker maritime_mvp.api.main:app --chdir src --bind 0.0.0.0:$PORT --workers 2 --timeout 90
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false                       # set in Render → Environment (include ?sslmode=require)
      - key: PSIX_WSDL
        value: https://cgmix.uscg.mil/xml/PSIXData.asmx?WSDL
      - key: PSIX_VERIFY_SSL
        value: "false"
      - key: ALLOW_ORIGINS                 # optional: lock CORS to your static site domain
        value: "*"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: maritime-cache
          property: connectionString

  - type: keyvalue
    name: maritime-cache
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - type: static
    name: maritime-mvp-frontend
    staticPublishPath: frontend
